[versions]
agp = "8.12.1"
androidTools = "31.12.1"
androidx-credentials = "1.5.0"
android-compileSdk = "36"
android-wear-compileSdk = "36"
android-minSdk = "26"
androidx-activityCompose = "1.10.1"
androidx-appcompat = "1.7.1"
androidx-constraintlayout = "2.2.1"
googleid = "1.1.1"
androidx-core-ktx = "1.17.0"
androidx-espresso-core = "3.7.0"
androidx-lifecycle = "2.9.2"
logback-classic = "1.5.18"
androidx-material = "1.12.0"
androidx-test-junit = "1.3.0"
libphonenumber = "9.0.12"
activity-compose = "1.10.1"
aws = "2.81.0"
places = "4.4.1"
desugar-jdk-libs = "2.1.5"
build-konfig = "0.17.1"
compose-bom = "2025.08.00"
compose-navigation = "2.9.3"
espresso = "3.7.0"
coil = "3.3.0"
firebase-ui = "9.0.0"
gmsPlugin = "4.4.3"
ksp = "2.2.0-2.0.2"
facebook = "18.1.3"
firebaseBom = "34.1.0"
firebaseCrashlyticsPlugin = "3.0.6"
firebasePerfPlugin = "2.0.1"
jacoco = "0.8.12"
junit = "4.13.2"
junit-ext = "1.3.0"
kotlin = "2.2.10"
kotlinx-coroutines = "1.10.2"
ktor = "3.2.3"
kotlinx-serialization = "1.9.0"
koin-bom = "4.1.0"
androidx-datastore = "1.1.7"
material-icons-extended = "1.7.8"
korio = "4.0.3"
mockitoCore = "5.19.0"
mockitoKotlin = "6.0.0"
xmlutil = "0.91.2"
jetpack-navigation = "2.8.0-alpha13"
core-splashscreen = "1.0.1"
skiko = "0.9.22"
app-update = "2.1.0"
room = "2.7.2"
truth = "1.4.4"
androidxLintGradle = "1.0.0-alpha05"
composeHotReload = "1.0.0-beta05"
coroutinesTest = "1.10.2"
androidx-arch-core = "2.2.0"
wear-compose = "1.5.0-rc02"
navigation = "2.9.3"
wear-ongoing = "1.0.0"
compose-plugin = "1.8.2"
revenuecat = "9.2.0"
google-ads = "24.5.0"
billing = "8.0.0"
media = "1.1.0"
mlkit = "16.1.7"
kmpauth = "2.3.0-beta01"

[libraries]
facebook-sdk = { module = "com.facebook.android:facebook-android-sdk", version.ref = "facebook" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-ext = { module = "androidx.test.ext:junit", version.ref = "junit-ext" }
androidx-arch-core = { module = "androidx.arch.core:core-testing", version.ref = "androidx-arch-core" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-service =  { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "androidx-lifecycle" }
androidx-lifecycle-common =  { group = "androidx.lifecycle", name = "lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime =  { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata =  { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lint-gradle = { group = "androidx.lint", name = "lint-gradle", version.ref = "androidxLintGradle" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-compose-core = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
coil-mp = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktor" }
ktor-network-tls = { module = "io.ktor:ktor-network-tls", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-classic" }
places = { group = "com.google.android.libraries.places", name = "places", version.ref = "places" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-core-coroutines = { module = "io.insert-koin:koin-core-coroutines" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-cloud-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-storage = { module = "com.google.firebase:firebase-storage" }
firebase-performance = { group = "com.google.firebase", name = "firebase-perf" }
firebase-auth = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-ui-auth = { module = "com.firebaseui:firebase-ui-auth", version.ref = "firebase-ui" }

koin-android = { module = "io.insert-koin:koin-android" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-compose-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation" }
connect-sdk-android = { module = "com.connectsdk:connect-sdk-android", version = "1.6.0" }
androidx-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "androidx-datastore" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidx-datastore" }
xmlutil-core = { module = "io.github.pdvrieze.xmlutil:core", version.ref = "xmlutil" }
xmlutil-serialization = { module = "io.github.pdvrieze.xmlutil:serialization", version.ref = "xmlutil" }
korio = { module = "com.soywiz.korlibs.korio:korio", version = "korio" }
androidx-navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "jetpack-navigation" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }
skiko = { module = "org.jetbrains.skiko:skiko", version.ref = "skiko" }
google-play-app-update = { module = "com.google.android.play:app-update", version.ref = "app-update" }
google-play-app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "app-update" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billing" }
kmpauth-google = { module = "io.github.mirzemehdi:kmpauth-google", version.ref = "kmpauth" }
kmpauth-uihelper = { module = "io.github.mirzemehdi:kmpauth-uihelper", version.ref = "kmpauth" }

androidx-media = { group = "androidx.media", name = "media", version.ref = "media" }
mlkit-faceDetection = { module = "com.google.mlkit:face-detection", version.ref = "mlkit" }
google-libphonenumber = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "libphonenumber" }
androidx-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "androidx-credentials" }
androidx-credentials-play-services = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "androidx-credentials" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar-jdk-libs" }

#Room
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

#AWS
aws-s3 = { module = "com.amazonaws:aws-android-sdk-s3", version.ref = "aws" }
aws-core = { module = "com.amazonaws:aws-android-sdk-core", version.ref = "aws" }
aws-rekognition = { module = "com.amazonaws:aws-android-sdk-rekognition", version.ref = "aws" }
aws-dynamodb = { module = "com.amazonaws:aws-android-sdk-ddb", version.ref = "aws" }
aws-lambda = { module = "com.amazonaws:aws-android-sdk-lambda", version.ref = "aws" }
# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
firebase-crashlytics-gradlePlugin = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsPlugin" }
firebase-performance-gradlePlugin = { group = "com.google.firebase", name = "perf-plugin", version.ref = "firebasePerfPlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
buildKonfig-gradlePlugin = { group = "com.codingfeline.buildkonfig", name = "buildkonfig-gradle-plugin", version.ref = "build-konfig" }

kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesTest" }
# wear
wear-compose-material = { group = "androidx.wear.compose", name = "compose-material", version.ref = "wear-compose" }
compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "wear-compose" }
wear-compose-foundation = { group = "androidx.wear.compose", name = "compose-foundation", version.ref = "wear-compose" }
wear-compose-navigation = { group = "androidx.wear.compose", name = "compose-navigation", version.ref = "wear-compose" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }

wear-compose-tooling-preview = { group = "androidx.wear.compose", name = "compose-ui-tooling" }
wear-ongoing = { group = "androidx.wear", name = "wear-ongoing", version.ref = "wear-ongoing" }

revenuecat = { module = "com.revenuecat.purchases:purchases", version.ref = "revenuecat" }
revenuecat-ui = { module = "com.revenuecat.purchases:purchases-ui", version.ref = "revenuecat" }
google-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "google-ads" }

# Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons-extended" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest"}
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "compose-navigation" }

[plugins]
buildKonfig = { id = "com.codingfeline.buildkonfig", version.ref = "build-konfig" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerfPlugin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "gmsPlugin" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }

# Plugins defined by this project
nowinandroid-android-application = { id = "nowinandroid.android.application" }
nowinandroid-android-application-compose = { id = "nowinandroid.android.application.compose" }
nowinandroid-android-application-firebase = { id = "nowinandroid.android.application.firebase" }
nowinandroid-android-application-flavors = { id = "nowinandroid.android.application.flavors" }
nowinandroid-android-application-jacoco = { id = "nowinandroid.android.application.jacoco" }
nowinandroid-android-feature = { id = "nowinandroid.android.feature" }
nowinandroid-android-library = { id = "nowinandroid.android.library" }
nowinandroid-android-library-compose = { id = "nowinandroid.android.library.compose" }
nowinandroid-android-library-jacoco = { id = "nowinandroid.android.library.jacoco" }
nowinandroid-android-lint = { id = "nowinandroid.android.lint" }
nowinandroid-android-room = { id = "nowinandroid.android.room" }
nowinandroid-android-test = { id = "nowinandroid.android.test" }
nowinandroid-hilt = { id = "nowinandroid.hilt" }
nowinandroid-jvm-library = { id = "nowinandroid.jvm.library" }

[bundles]
tests = [ "junit", "mockito-core", "mockito-kotlin", "kotlinx-coroutines-test", "androidx-arch-core"]
androidTests = [ "junit-ext", "androidx-espresso-core"]
composeDebug = ["compose-ui-tooling"]
wear-compose = ["compose-activity", "wear-compose-tooling-preview", "wear-compose-material", "wear-compose-foundation", "wear-compose-navigation"]
lifecycle = ["androidx-lifecycle-service", "androidx-lifecycle-common", "androidx-lifecycle-runtime", "androidx-lifecycle-livedata", "androidx-lifecycle-viewmodel"]